Repository ucsb-cs156-s24/proj-organic-s24-5pm-3, pull requests merged in 2024-06, with the labels that each got.

#69 pc - move commented out lines into javadoc
  src/main/java/edu/ucsb/cs156/organic/controllers/CoursesController.java
Labels: branch-to-branch

#71 pc - spike of better error handling;
  frontend/src/main/components/Courses/GitHubAppTips.js
  frontend/src/main/pages/CoursesEditPage.js
  frontend/src/tests/pages/CoursesEditPage.test.js
  src/main/java/edu/ucsb/cs156/github/GitHubApp.java
  src/main/java/edu/ucsb/cs156/organic/controllers/CoursesController.java
  src/main/java/edu/ucsb/cs156/organic/models/OrgStatus.java
  src/test/java/edu/ucsb/cs156/organic/controllers/CoursesControllerTests.java
Labels: branch-to-branch

#53 Created Course Show Page with Storybook Page
  frontend/src/App.js
  frontend/src/main/pages/CoursesShowPage.js
  frontend/src/stories/pages/CourseShowPage.stories.js
  frontend/src/tests/components/Courses/CoursesTable.test.js
  frontend/src/tests/pages/CoursesShowPage.test.js
  src/main/java/edu/ucsb/cs156/organic/controllers/CoursesController.java
Labels: FIXME-See CR

#60 Added tooltip UX to School variables(abbrev, desc, regex)
  frontend/src/fixtures/schoolsFixtures.js
  frontend/src/main/components/School/SchoolForm.js
  frontend/src/main/components/School/SchoolTable.js
  frontend/src/tests/components/School/SchoolForm.test.js
  frontend/src/tests/components/School/SchoolTable.test.js
  frontend/src/tests/pages/School/SchoolEditPage.test.js
  src/main/java/edu/ucsb/cs156/organic/controllers/SchoolController.java
  src/test/java/edu/ucsb/cs156/organic/controllers/SchoolControllerTests.java
Labels: 10

#67 Staff page staff list and add staff
  frontend/src/App.js
  frontend/src/main/components/Courses/AddCourseStaffForm.js
  frontend/src/main/pages/CoursesAddStaffPage.js
  frontend/src/main/pages/CoursesStaffPage.js
  frontend/src/tests/components/Courses/AddCourseStaffForm.test.js
  frontend/src/tests/pages/CoursesAddStaffPage.test.js
  frontend/src/tests/pages/CoursesStaffPage.test.js
Labels: Merge Candidate-dokku
