Repository ucsb-cs156-s24/proj-organic-s24-5pm-3, pull requests merged in 2024-05, with the labels that each got.

#25 FEATURE: H2Console Option on Navbar for Development
  src/main/resources/application-development.properties
  src/main/resources/application-production.properties
Labels: FIXME-Peer CR needed

#51 Pc fix interceptors
  src/main/java/edu/ucsb/cs156/organic/interceptors/RoleUserInterceptor.java
  src/main/java/edu/ucsb/cs156/organic/interceptors/RoleUserInterceptorAppConfig.java
  src/test/java/edu/ucsb/cs156/organic/interceptors/RoleUserInterceptorTests.java
Labels: staff-pr, 0

#47 [merge] upgrading to spring3
  pom.xml
  src/main/java/edu/ucsb/cs156/organic/config/SecurityConfig.java
  src/main/java/edu/ucsb/cs156/organic/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/organic/controllers/CoursesController.java
  src/main/java/edu/ucsb/cs156/organic/controllers/FrontendProxyController.java
  src/main/java/edu/ucsb/cs156/organic/controllers/SchoolController.java
  src/main/java/edu/ucsb/cs156/organic/entities/Course.java
  src/main/java/edu/ucsb/cs156/organic/entities/School.java
  src/main/java/edu/ucsb/cs156/organic/entities/Staff.java
  src/main/java/edu/ucsb/cs156/organic/entities/Student.java
  src/main/java/edu/ucsb/cs156/organic/entities/User.java
  src/main/java/edu/ucsb/cs156/organic/entities/UserEmail.java
  src/main/java/edu/ucsb/cs156/organic/entities/jobs/Job.java
  src/main/java/edu/ucsb/cs156/organic/interceptors/RoleUserInterceptor.java
  src/main/resources/application-production.properties
  src/test/java/edu/ucsb/cs156/organic/controllers/CoursesControllerTests.java
  src/test/java/edu/ucsb/cs156/organic/controllers/SchoolControllerTests.java
  src/test/java/edu/ucsb/cs156/organic/testconfig/MockCurrentUserServiceImpl.java
  src/test/java/edu/ucsb/cs156/organic/testconfig/TestConfig.java
Labels: 10

#42 CRUD STAFF OPERATION Go to Staff Page from Course Page
  frontend/src/App.js
  frontend/src/main/pages/CoursesStaffPage.js
  frontend/src/tests/pages/CoursesStaffPage.test.js
  src/main/resources/application-development.properties
  src/main/resources/application-production.properties
Labels: FIXME-See CR

#52 Aaron home page info
  frontend/src/main/pages/HomePage.js
  frontend/src/tests/pages/HomePage.test.js
  src/main/java/edu/ucsb/cs156/organic/interceptors/RoleUserInterceptor.java
  src/main/java/edu/ucsb/cs156/organic/interceptors/RoleUserInterceptorAppConfig.java
  src/test/java/edu/ucsb/cs156/organic/interceptors/RoleUserInterceptorTests.java
Labels: 10
